### ISSUE TITLE
[Bug] Clear Conversation not working for different user

### ISSUE THREAD

**Issue by ElioErrico** [cheshire-cat-ai/admin-vue#113]
** Changing user identification**
I changed the user in "vite.config.mts" admin/admin to user/user file:
```
		{
			name: 'configure-token',
			configureServer(server) {
				return () => {
					server.middlewares.use(async (_, res, next) => {
						const output = await (
							await fetch('http://localhost:1865/auth/token', {
								method: 'POST',
								headers: {
									'Content-Type': 'application/json',
								},
								body: JSON.stringify({
									username: 'user',
									password: 'user',
								}),
							})
						).json()
						res.setHeader('Set-Cookie', `ccat_user_token=${output.access_token}`)
						next()
					})
				}
			},
		},
	],
```

**Behavior**
The code works correctly and it creates an interface with 'user' privileges.

**Not working wipe chat history**
It does not work the 'wipe chat history method'.
It says 'Invalid credentials'.

**Note**
Other things related to user_id  works correctly like: export_conversation, separated chats or when it loads the chat history after you refresh the page.

**Comment by pieroit** [comment]
@ElioErrico  what happened?

**Comment by ElioErrico** [comment]
It was my mistake, I did not give delete memory privilege to that user (I thought it was chat delete privileges)
