### ISSUE TITLE
Switch episodic/declarative collections on/off

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#14]
**Is your feature request related to a problem? Please describe.**
Users may be interested in activating or deactivating one or both memories.

**Describe the solution you'd like**
Send via websocket a json containing not only the text but also prompt settings

```json
{
    "text": "....",
    "prompt_settings": {
        "use_declatarive_memory": false,
        "use_episodic_memory": true,
    }
}
```

**Describe alternatives you've considered**
After a conversation in the Discord we reached agreement on these as the most useful options at the moment.

@zAlweNy26 @cristianorevil feel free to redesign wireframe and datastructure as you see fit or involve the community in case you want support

**Comment by zAlweNy26** [comment]
Awesome

**Comment by cristianorevil** [comment]
Perfect. I open a PR on the core to manage the new prompt settings
