### ISSUE TITLE
Chat settings opens up the SidePanel to customize the prompt

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#16]
As discussed by @zAlweNy26 and @nicola-corbellini , we could have an easy way to customize the prompt from the admin by expanding Chat Settings

1 - chat settings open up in the side panel adn not in the modal
2 - there is also a textarea with prompt instructions (who the cat is)
3 - the prompt is sent via websocket under `prompt_settings.prefix`

![Screenshot from 2023-06-22 18-40-15](https://github.com/cheshire-cat-ai/admin-vue/assets/6328377/cfa19739-11d7-4005-8238-d60891c7b3d5)

**Comment by zAlweNy26** [comment]
Done 💯

**Comment by pieroit** [comment]
Thanks will align core soon!
