### ISSUE TITLE
[Bug] Not updating view after wiping memories or removing plugins

### ISSUE THREAD

**Issue by Pingdred** [cheshire-cat-ai/admin-vue#19]
**Describe the bug**
Memories count in memory page is not updated after wipe.

**To Reproduce**
1. Go to the memory page
2. Choose a collection to wipe
3. Click on WIPE

**Expected behavior**
After the wipe the memories count should be 0.

**Comment by zAlweNy26** [comment]
Unfortunately I am already aware of this problem, there is a similar one on the plugins page. I will try to fix it as soon as possible.

**Comment by EugenioPetulla** [comment]
We still have this issue open because the core still doesn't has this kind of notification implemented (uninstall and wipe done).

I suggest to remove the "good first issue" label and to keep track of this also in the core by opening a specific issue there then linking it here.
