### ISSUE TITLE
Shorten long messages in chat

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#20]
**Is your feature request related to a problem? Please describe.**
When an user copy/pasters a long text in the chat, the backend gives an error (will be fixed) and in any case the message bubble would become huge.

**Describe the solution you'd like**
Backend should be able to deal with long texts, and the admin just make the message box small so it does not occupy visual space

**Comment by zAlweNy26** [comment]
Which should be the characters limit before showing the "Read More" button?

**Comment by pieroit** [comment]
I propose 5000 chars, which should be around 2000 tokens, which is half the context length for chatGPT

**Comment by zAlweNy26** [comment]
The same thing should happen for the cat response or just for the user?

**Comment by pieroit** [comment]
> The same thing should happen for the cat response or just for the user?

Ok if it is not complex, otherwise the user side should be enough
