### ISSUE TITLE
Drag & drop for both documents and URLs

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#21]
**Is your feature request related to a problem? Please describe.**

As a plus, would be nice to have drag and drop into the chat to ingest documents and URLs instead of buttons only.

**Comment by zAlweNy26** [comment]
Also added a copy-paste handler with the same behavior as drag & drop

**Comment by pieroit** [comment]
> Also added a copy-paste handler with the same behavior as drag & drop

Beautiful! I'll try it now
