### ISSUE TITLE
`Save` button in LLM and Embedder settings should only be enabled when required fields are set

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#27]
**Describe the bug**
You can save an empty configuration from LLM/Embedder settings side panel
(look at the Save button)

![Screenshot from 2023-07-15 22-43-09](https://github.com/cheshire-cat-ai/admin-vue/assets/6328377/97e53451-e7d1-444c-b3ea-fccceea7070d)

**To Reproduce**
1. Select an LLM configuration requiring a field (example openai key)
2. leave the field empty
3. hit the Save button

**Expected behavior**
Save button is only enabled when required fields are set

**Comment by zAlweNy26** [comment]
You are right, I didn't think about that!
