### ISSUE TITLE
First click on memory plot does not open the SidePanel

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#31]
**To Reproduce**
1. Go into Memory page
2. Do a search and wait for the points to show up in the plot
3. Click on a memory point 
4. Click again

**Expected behavior**
Should work on the first click

**Comment by zAlweNy26** [comment]
Yeah I know, it's a problem that appeared with the new plot library. I asked @EugenioPetulla to help me when he can :)

**Comment by pieroit** [comment]
Low priority, just having the issue open to free up our minds

**Comment by pieroit** [comment]
Nice! Thanks
