### ISSUE TITLE
[Feature] Add `Import Memories` button in the "Memory" page

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/admin-vue#44]
It would be nice to have another `Import Memories` button close to the `Export Memories` one, in the "Memory" page.

Here is an example proposal (the button color is random):
![Frame 1](https://github.com/cheshire-cat-ai/admin-vue/assets/67009524/db8076c0-65f6-4396-ba8f-3f1723c6432a)

P.S.: an issue like this, with a wireframe like this può accompagnare solo

**Comment by nicola-corbellini** [comment]
Ah didn't think about it, but it could still make sense. After all, there is the upload memory option under the bolt which is always available.

**Comment by zAlweNy26** [comment]
Even if I don't like it, I did it:
![image](https://github.com/cheshire-cat-ai/admin-vue/assets/41266342/baae3a3f-bb08-4297-accc-7a1f8be3b90e)

**Comment by pieroit** [comment]
What do you think about keeping it, and move it when we redesign the top of page for memory search filters

**Comment by zAlweNy26** [comment]
Yeah no problem
