### ISSUE TITLE
Link to guide on plugin publishing (suggestion)

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#52]
Can we find a way to link from the `Plugins` page the docs about plugin [building]() and [publishing](https://cheshire-cat-ai.github.io/docs/plugins-registry/publishing-plugin/)? Maybe the [template](https://cheshire-cat-ai.github.io/docs/plugins-registry/plugin-from-template/)?

**Comment by zAlweNy26** [comment]
Yeah no problem, let's wireframe it

**Comment by zAlweNy26** [comment]
Can I close this? @pieroit @EugenioPetulla

**Comment by pieroit** [comment]
Please leave open so we (or others) can suggest wireframe/ideas

**Comment by EugenioPetulla** [comment]
Agree. Let's get this ferment.
