### ISSUE TITLE
All dates in european format DD/MM/YYYY

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#61]
Because EU > US

![image](https://github.com/cheshire-cat-ai/admin-vue/assets/6328377/82377695-7bb8-4325-abe4-88e6754be164)

**Comment by zAlweNy26** [comment]
Funny issue, but the dates are converted to locale strings, so it's your fat-mc-weaponized-american browser that shows the date in that format 🤣
