### ISSUE TITLE
[Bug] plugins page scrolls to the bottom repeatedly if the cat is talking.

### ISSUE THREAD

**Issue by jimmyjam-50066** [cheshire-cat-ai/admin-vue#67]
**Describe the bug**
plugins page scrolls to the bottom repeatedly if the cat is talking.

**To Reproduce**
1.) talk to the cat
2.) while the cat is thinking get bored and click on plugins.
3.) after the cat is done thinking he'll start talking and the plugins page will repeatedly scroll to the bottom until the cat is finished.

**Expected behavior**
I'm not sure I guess... a normally functioning plugins page since the message window isn't visible.

**Screenshots**
Here's a video instead. 
https://drive.google.com/file/d/1CyHpf6qOMuRuinrCoBqkjG0RSHyOkqUW/view?usp=drive_link

**Additional context**

**Comment by zAlweNy26** [comment]
@kodaline would you like to do this one?

**Comment by kodaline** [comment]
> @kodaline would you like to do this one?

Ofc! I want to become a master in Vue like you <3

**Comment by zAlweNy26** [comment]
@kodaline spoiler: you can do it even without being assigned to it 🤪

**Comment by kodaline** [comment]
> @kodaline spoiler: you can do it even without being assigned to it 🤪

I know LOL but I like to see me assigned ahahahaha
