### ISSUE TITLE
[BAD BUG] Cached LLM/Embedder settings overwrite actual settings and mess up updates

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#69]
Admin keeps a cached version of LLM/embedder settings that has side effects on other settings visualization and save/load.

![image](https://github.com/cheshire-cat-ai/admin-vue/assets/6328377/742c6de0-2479-4f3f-b38f-94e80d8cd23a)

In this case `model` is not visible while having a clear default in factory.
IF any setting is saved, old config and new one gets mixed (breaking installation)

IMPORTANT: **Do not cache settings**, as it happens in plugins, make a request every time the panel opens up

**Comment by kodaline** [comment]
@zAlweNy26 this should be already solved on develop, right?

**Comment by zAlweNy26** [comment]
@kodaline nope

**Comment by pieroit** [comment]
Should we organize a group debug?
Let's fix this

**Comment by pieroit** [comment]
Works now!
Thanks @zAlweNy26
