### ISSUE TITLE
Show upgrade button for plugins

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#77]
`core` has been updated to show whether a plugin has a new version from registry

- info is shown for the `GET /plugins/` endpoint
- inside an installed plugin data, there is a key `upgrade`:
  - `null` if there are no new versions
  - string (e.g. "1.3.0") if there is a new version

Example of not upgradable plugin:
```json
{
      "id": "purrcast_podcast_finder",
      "name": "PurrCast - Podcast Finder",
      "description": "Search for public podcast shows and episodes on Spreaker.",
      "author_name": "Eugenio Petullà",
      "author_url": "https://github.com/EugenioPetulla",
      "plugin_url": "https://github.com/EugenioPetulla/PurrCast_Podcast_Finder",
      "tags": "podcast, multimedia, entertainment",
      "thumb": "https://raw.githubusercontent.com/EugenioPetulla/PurrCast_Podcast_Finder/main/logo.png",
      "version": "1.1.0",
      "active": true,
      "upgrade": null,
      "hooks": [],
      "tools": []
},
```
Example of upgradable plugin:
```json
{
      "id": "purrcast_podcast_finder",
      "name": "PurrCast - Podcast Finder",
      "description": "Search for public podcast shows and episodes on Spreaker.",
      "author_name": "Eugenio Petullà",
      "author_url": "https://github.com/EugenioPetulla",
      "plugin_url": "https://github.com/EugenioPetulla/PurrCast_Podcast_Finder",
      "tags": "podcast, multimedia, entertainment",
      "thumb": "https://raw.githubusercontent.com/EugenioPetulla/PurrCast_Podcast_Finder/main/logo.png",
      "version": "1.1.0",
      "active": true,
      "upgrade": "1.2.0",
      "hooks": [],
      "tools": []
},
```

Endpoint to update and checks to delete the older version and upload the new are not yet there.
We can just use the already present endpoint to install plugins from registry and `core` can do the checks, so admin side you can just get the plugin URL and use the endpoint `POST /plugins/upload/registry`

**Comment by pieroit** [comment]
Just realized it may work only if you search the plugin :(
In that case core will need to explicitly ask registry to send info on plugins that are already installed

**Comment by zAlweNy26** [comment]
> Just realized it may work only if you search the plugin :( In that case core will need to explicitly ask registry to send info on plugins that are already installed

I didn't understand the problem, can we talk about this in a call? Also to wireframe the feature.

**Comment by pieroit** [comment]
> > Just realized it may work only if you search the plugin :( In that case core will need to explicitly ask registry to send info on plugins that are already installed
> 
> I didn't understand the problem, can we talk about this in a call? Also to wireframe the feature.

Yes ;)

**Comment by zAlweNy26** [comment]
Added in develop

**Comment by pieroit** [comment]
> Added in develop

you fast
