### ISSUE TITLE
[Feature] Mathematical Formulae should be correctly displayed

### ISSUE THREAD

**Issue by FedeDC512** [cheshire-cat-ai/admin-vue#79]
I think it would be really convenient if the Mathematical Formulas were rendered and displayed correctly, as is the case with ChatGPT. In my case I tested Markdown, KaTeX and LaTeX, and none of the three are displayed correctly.

**Additional context**
![image](https://github.com/cheshire-cat-ai/admin-vue/assets/78120567/24a07b00-b049-42d5-bc7c-ced646b60c38)
![image](https://github.com/cheshire-cat-ai/admin-vue/assets/78120567/fa56d72a-2865-4948-bde0-1cfc1b0bc93f)

**Comment by pieroit** [comment]
Interesting and a good idea, but I guess complicated to implement, what do you think @zAlweNy26 ?

Please @FedeDC512 remember the admin is just to admin and configure the cat, if you want a custom experience you should develop a custom widget and talk to the cat via API/websocket

**Comment by zAlweNy26** [comment]
@pieroit I don't know if there is any plugin for the markdown parser library I'm currently using. I can search and let you know.

**Comment by zAlweNy26** [comment]
Unfortunately the only existing library is too old and the effort is not worth it. Closing as not needed.
