### ISSUE TITLE
Memory page not updated after wiping collections

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#80]
When a user wipes a collection or all of them, both the plot and the counts near the `Wipe` button are not updated.
If you refresh the page, they are updated

**Comment by TobioDev** [comment]
Hi! I confirm that I have encountered a bug related to updating the graphics, and the counter next to the ‘Wipe’ button always displays ‘null’.

![image](https://github.com/cheshire-cat-ai/admin-vue/assets/19150611/00d9db0f-bbf2-4418-84a4-57740acd787c)
