### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/admin-vue#93]
Logout button in the admin should:
1. delete all cookies*
2. redirect to `/auth/login`

* The login page already deletes cookies, but just to be sure :D

**Comment by zAlweNy26** [comment]
Where should it be placed?

**Comment by pieroit** [comment]
> Where should it be placed?

What do you think of something like this?

![image](https://github.com/user-attachments/assets/9b058618-8adb-4664-a458-0c766dcee9e6)

Top right, small circle, and a menu (right now just the user name and the logout button)

**Comment by zAlweNy26** [comment]
I prefer something like this:
![image](https://github.com/user-attachments/assets/eee5f69e-6288-421d-addc-7af2c5fe1008)

CC: @kodaline @scicco

**Comment by kodaline** [comment]
> I prefer something like this

What do you think about this @pieroit @zAlweNy26 ? Not yet fully finished, but I thought about keeping the same style of the bottom left dropdown from where we Upload files/urls, clear conversation etc

![Screenshot from 2024-10-09 22-40-15](https://github.com/user-attachments/assets/b54356eb-8422-4766-bbc4-6825c52c6e68)

**Comment by pieroit** [comment]
> > I prefer something like this
> 
> What do you think about this @pieroit @zAlweNy26 ? Not yet fully finished, but I thought about keeping the same style of the bottom left dropdown from where we Upload files/urls, clear conversation etc
> 
> ![Screenshot from 2024-10-09 22-40-15](https://private-user-images.githubusercontent.com/9247877/375125195-b54356eb-8422-4766-bbc4-6825c52c6e68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MTI2NDgsIm5iZiI6MTcyODUxMjM0OCwicGF0aCI6Ii85MjQ3ODc3LzM3NTEyNTE5NS1iNTQzNTZlYi04NDIyLTQ3NjYtYmJjNC02ODI1YzUyYzZlNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMjIxOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QwOTlkNDJlMzFkYTAxYjI2ZDVmNzhmZjljNmQ0OTA5Mjk1YWEwYmVlZTQwZTJjMTQwODBmMTA1Y2QwNjUxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bsuvWYoRJXNhYt5XQjvbN-pHj4IPnA_MUVBqGaq8bDY)

Awesome, looks goog to me!

About consistency, in the future we can start wrapping up styles in components and create our own design system. With due relax ;)

**Comment by kodaline** [comment]
> Awesome, looks goog to me!
> 
![Screenshot from 2024-10-10 10-58-40](https://github.com/user-attachments/assets/4f3cb7e7-5421-44dd-bc7f-5c82d808d2b5)

It got some little updates

**Comment by zAlweNy26** [comment]
I think it should be on the right, not left :)

**Comment by kodaline** [comment]
> I think it should be on the right, not left :)

do you mean the dropdown menu to be placed on the bottom right of the user icon?

**Comment by zAlweNy26** [comment]
> > I think it should be on the right, not left :)
> 
> do you mean the dropdown menu to be placed on the bottom right of the user icon?

No I mean the text, it should be all on the right

**Comment by kodaline** [comment]
> > do you mean the dropdown menu to be placed on the bottom right of the user icon?
> 
> No I mean the text, it should be all on the right

Oh ok, when I do it, it looks like this

![Screenshot from 2024-10-10 15-03-31](https://github.com/user-attachments/assets/7dca19b1-88ea-47a1-9b4a-451533ac54b4)
The fact that the line with the username does not align with the text of the other ones is disturbing me XD

Might solve it putting the two icons, theme change and login, on the left before the text? but I don't think I like it

**Comment by zAlweNy26** [comment]
It seems fine to me, just use a different color for the "Signed in as", so to differ from the theme and logout buttons :)

**Comment by scicco** [comment]
hi, maybe splitting signed in as admin and the rest, with some border

```
-----------------------
   signed in as admin
-----------------------
       Change Theme ☀️
             Logout 🚪
-----------------------
```

**Comment by kodaline** [comment]
> It seems fine to me, just use a different color for the "Signed in as", so to differ from the theme and logout buttons :)

![Screenshot from 2024-10-10 16-10-42](https://github.com/user-attachments/assets/96c95c4e-0653-4a6c-958e-bc4e209a6a1f)

@scicco I don't know, I will try later on a border just between signed in and the rest, but the others seem too much to me

**Comment by scicco** [comment]
> @scicco I don't know, I will try later on a border just between signed in and the rest, but the others seem too much to me

yeah other borders are there just because i'm bad with ascii art, i only meant the inner one 😅
