### ISSUE TITLE
[Feature] permissions selection with multiselect

### ISSUE THREAD

**Issue by scicco** [cheshire-cat-ai/admin-vue#95]
**Describe the solution you'd like**

change permission management by using the vue-select library instead of checkboxes

**Comment by pinpolhoxx** [comment]
I think this will help you.
https://bit.ly/3TzaAQd
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by zAlweNy26** [comment]
Solved in #94
