### ISSUE TITLE
Obfuscating the key value in the LLM and embedder configuration screens

### ISSUE THREAD

**Issue by ptrpla** [cheshire-cat-ai/admin-vue#98]
**Is your feature request related to a problem? Please describe.**
Once added an API key, it is always visibile to the user in plain text and editable.

**Describe the solution you'd like**
For security reason (shoulder surfing or even someone hijacking an account and using the key), I would make the API keys obfuscated and not editable - the user would need to delete the key and add a new one.

**Comment by zAlweNy26** [comment]
As discussed with @pieroit , at the moment the api keys are still clearly visible in the network tab of devtools when receiving from backend, making this change quite surmountable.

**Comment by zAlweNy26** [comment]
Also, the admin can't know which property is a sensitive field, as they can extended by plugins.
