### ISSUE TITLE
Better context on the toggle switch to activate a plugin

### ISSUE THREAD

**Issue by ptrpla** [cheshire-cat-ai/admin-vue#99]
**Is your feature request related to a problem? Please describe.**
After a plug-in is installed you need to click the toggle switch and right now there is no clear visual cue or action qualification via text, making it hard to guess for a user.
 
**Describe the solution you'd like**
It would be best to add some text next to the toggle switch such as [Activate]

**Additional context**
<img width="1510" alt="Screenshot 2024-10-02 at 11 52 53" src="https://github.com/user-attachments/assets/b9aad947-7f19-40a5-9813-f0a463e19023">

**Comment by zAlweNy26** [comment]
Hi, the switch is usually quite straightforward, especially due to the colors changing whether it is on the right or left. There is also a notification that alerts you to the change.
